### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 'Umi' when using custom primers on edlib backend

### ISSUE THREAD

**Issue by jkbenotmane** [epi2me-labs/pychopper#15]
Hello Pychopper developers,

I am experiencing an issue while using Pychopper with custom 10X primers to restore directionality in my Oxford Nanopore reads. I encountered a `TypeError` in the Pychopper script, specifically related to a missing positional argument 'Umi' in a lambda function. Here is the error message I received:

My Primers look like this:

```
>TSO
AAGCAGTGGTATCAACGCAGAG
>Read1
CTACACGACGCTCTTCCGATCT
```

The configuration .txt. looks like this:

```
+:Read1,-TSO|-:TSO,-Read1
```

I use this command:

```
  mkdir "${OUTFOLDER}"/PYCHOPPER
  pychop_dir="${OUTFOLDER}"/PYCHOPPER

  pychopper \
    -m edlib \
    -r "${LOGS}"/"${SAMPLE_NAME}"_Pychopper_report.pdf \
    -S "${LOGS}"/"${SAMPLE_NAME}"_Pychopper_report.tsv \
    -b "${PRIMERS}" \
    -c "${PRIMER_CONFIGURATION}" \
    -U \
    "${INPUT_FASTQ}" \
    "${pychop_dir}"/"${SAMPLE_NAME}"_pychopped.fastq \
    2> "${LOGS}"/"${SAMPLE_NAME}"_Pychopper_stderr.txt

```

This is the Error I am experiencing:

```
Using kit: PCS109
Configurations to consider: "+:Read1,-TSO|-:TSO,-Read1"
Counting fastq records in input file: /media/jkb/JKB_500GB/Raw_Nanopore/Example_TCR.fastq
Total fastq records in input file: 20000
Tuning the cutoff parameter (q) on 5572 sampled reads (50.0%) passing quality filters (Q >= 7.0).
Optimizing over 30 cutoff values.

  0%|          | 0/30 [00:00<?, ?it/s]
  3%|▎         | 1/30 [00:00<00:13,  2.17it/s]
  7%|▋         | 2/30 [00:00<00:12,  2.18it/s]
 10%|█         | 3/30 [00:01<00:12,  2.22it/s]
 13%|█▎        | 4/30 [00:01<00:11,  2.24it/s]
 17%|█▋        | 5/30 [00:02<00:11,  2.21it/s]
 20%|██        | 6/30 [00:02<00:10,  2.21it/s]
 23%|██▎       | 7/30 [00:03<00:10,  2.12it/s]
 27%|██▋       | 8/30 [00:03<00:10,  2.13it/s]
 30%|███       | 9/30 [00:04<00:10,  2.01it/s]
 33%|███▎      | 10/30 [00:04<00:10,  1.90it/s]
 37%|███▋      | 11/30 [00:05<00:10,  1.81it/s]
 40%|████      | 12/30 [00:06<00:10,  1.72it/s]
 43%|████▎     | 13/30 [00:06<00:10,  1.69it/s]
 47%|████▋     | 14/30 [00:07<00:09,  1.63it/s]
 50%|█████     | 15/30 [00:07<00:09,  1.63it/s]
 53%|█████▎    | 16/30 [00:08<00:08,  1.58it/s]
 57%|█████▋    | 17/30 [00:09<00:08,  1.56it/s]
 60%|██████    | 18/30 [00:09<00:07,  1.56it/s]
 63%|██████▎   | 19/30 [00:10<00:07,  1.53it/s]
 67%|██████▋   | 20/30 [00:11<00:06,  1.53it/s]
 70%|███████   | 21/30 [00:12<00:06,  1.47it/s]
 73%|███████▎  | 22/30 [00:12<00:05,  1.46it/s]
 77%|███████▋  | 23/30 [00:13<00:04,  1.42it/s]
 80%|████████  | 24/30 [00:14<00:04,  1.41it/s]
 83%|████████▎ | 25/30 [00:14<00:03,  1.39it/s]
 87%|████████▋ | 26/30 [00:15<00:02,  1.37it/s]
 90%|█████████ | 27/30 [00:16<00:02,  1.36it/s]
 93%|█████████▎| 28/30 [00:17<00:01,  1.35it/s]
 97%|█████████▋| 29/30 [00:17<00:00,  1.35it/s]
100%|██████████| 30/30 [00:18<00:00,  1.36it/s]
Best cutoff (q) value is 0.5172 with 61% of the reads classified.
Processing the whole dataset using a batch size of 2500:

  0%|          | 0/20000 [00:00<?, ?it/s]
  0%|          | 1/20000 [00:00<48:23,  6.89it/s]
  3%|▎         | 637/20000 [00:00<32:48,  9.84it/s]
  7%|▋         | 1410/20000 [00:00<22:03, 14.04it/s]
  9%|▉         | 1873/20000 [00:00<15:04, 20.04it/s]
 13%|█▎        | 2501/20000 [00:00<10:13, 28.54it/s]
 16%|█▌        | 3245/20000 [00:00<06:51, 40.71it/s]
 20%|█▉        | 3998/20000 [00:00<04:35, 58.02it/s]
 24%|██▍       | 4848/20000 [00:00<03:03, 82.64it/s]
 27%|██▋       | 5493/20000 [00:01<02:04, 116.55it/s]
 31%|███       | 6134/20000 [00:01<01:23, 165.21it/s]
 34%|███▍      | 6873/20000 [00:01<00:56, 233.73it/s]
 38%|███▊      | 7501/20000 [00:01<00:38, 321.42it/s]
 41%|████      | 8210/20000 [00:01<00:26, 450.34it/s]
 45%|████▌     | 9008/20000 [00:01<00:17, 627.63it/s]
 49%|████▉     | 9784/20000 [00:01<00:11, 866.56it/s]Traceback (most recent call last):
  File "/home/jkb/mambaforge/envs/NANOPORE/bin/pychopper", line 10, in <module>
    sys.exit(main())
  File "/home/jkb/mambaforge/envs/NANOPORE/lib/python3.9/site-packages/pychopper/scripts/pychopper.py", line 496, in main
    for batch in utils.batch(
  File "/home/jkb/mambaforge/envs/NANOPORE/lib/python3.9/site-packages/pychopper/utils.py", line 29, in batch
    yield list(chain([next(batchiter)], batchiter))
  File "/home/jkb/mambaforge/envs/NANOPORE/lib/python3.9/site-packages/pychopper/seq_utils.py", line 105, in readfq
    yield Seq(name.split(" ", 1)[0], name, seq, None)  # yield a fasta record instead
TypeError: <lambda>() missing 1 required positional argument: 'Umi'

 50%|█████     | 10000/20000 [00:02<00:02, 4805.37it/s]
```

Thank you for your help!

**Comment by zhenyuan992** [comment]
this is a bug... 
the namedtuple `Seq` has 5 arguments
https://github.com/epi2me-labs/pychopper/blob/92c3c2a861fb05f5ff9db0d7665dbad829e9d837/pychopper/common_structures.py#L6
but its usage here only have 4 arguments:
https://github.com/epi2me-labs/pychopper/blob/92c3c2a861fb05f5ff9db0d7665dbad829e9d837/pychopper/seq_utils.py#L105
@philres

**Comment by nrhorner** [comment]
Hi @jkbenotmane @zhenyuan992 

Thanks for bringing this to our attention. This issue is fixed in the latest version (2.7.6).  Could you please try that?

**Comment by nrhorner** [comment]
Closing due to lack of response

**Comment by zhenyuan992** [comment]
@nrhorner thanks for the fix.
i dont actually have the data to test with, but the code looks ok. there are exactly 4 commas
