### ISSUE TITLE
Installation not working properly

### ISSUE THREAD

**Issue by rb520826** [epi2me-labs/pychopper#43]
Thank you for the tool Pychopper. I have had no problems with it in the past but now I am having issues installing it properly. 

I create a conda environment. Then run this command: 
conda install -c nanoporetech -c conda-forge -c bioconda "nanoporetech::pychopper"

Once I have activated the conda environment and enter the command 'pychopper', I get the following error:

Traceback (most recent call last):
  File "/miniconda3/envs/nano/bin/pychopper", line 7, in <module>
    from pychopper.scripts.pychopper import main
  File "/miniconda3/envs/nano/lib/python3.10/site-packages/pychopper/scripts/pychopper.py", line 15, in <module>
    from pychopper import seq_utils as seu
  File "/miniconda3/envs/nano/lib/python3.10/site-packages/pychopper/seq_utils.py", line 5, in <module>
    from pysam import FastxFile
  File "/.local/lib/python3.10/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.1: cannot open shared object file: No such file or directory

Can you advise please?

**Comment by nrhorner** [comment]
> Hi @rb520826

> Could you try with Python 3.10 please?
I meant 3.8

Did you get round to trying this?

**Comment by nrhorner** [comment]
Thanks for getting back to me. I'm glad it works for you now
